name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.README_PAT }}

      - name: Generate dark stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default&role=OWNER,ORGANIZATION_MEMBER,COLLABORATOR&include_all_commits=true&count_private=true
          path: profile/dark_stats.svg
          token: ${{ secrets.README_PAT }}

      - name: Generate light stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default&role=OWNER,ORGANIZATION_MEMBER,COLLABORATOR&include_all_commits=true&count_private=true
          path: profile/light_stats.svg
          token: ${{ secrets.README_PAT }}

      - name: Generate dark top langs card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&langs_count=6&theme=dark
          path: profile/dark_top_langs.svg
          token: ${{ secrets.README_PAT }}

      - name: Generate light top langs card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&langs_count=6&theme=default
          path: profile/light_top_langs.svg
          token: ${{ secrets.README_PAT }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=readme-tools&repo=github-readme-stats
          path: profile/pin-readme-tools-github-readme-stats.svg
          token: ${{ secrets.README_PAT }}

      - name: Generate gist
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: gist
          options: id=0123456789abcdef
          token: ${{ secrets.README_PAT }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
